import type { FastifyInstance } from 'fastify'
import { request as httpRequest } from 'https'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { downloadManager } from '../services/download-manager.js'

const BILIBILI_API = 'passport.bilibili.com'

function biliGet(path: string): Promise<any> {
  return new Promise((resolve, reject) => {
    const req = httpRequest({
      hostname: BILIBILI_API,
      path,
      method: 'GET',
      headers: { 'User-Agent': 'PureDown/1.0', 'Referer': 'https://www.bilibili.com/' },
    }, (res) => {
      let data = ''
      res.on('data', (c: Buffer) => data += c.toString())
      res.on('end', () => {
        try { resolve(JSON.parse(data)) } catch { reject(new Error('Parse error')) }
      })
    })
    req.on('error', reject)
    req.end()
  })
}

export async function bilibiliAuthRoutes(app: FastifyInstance) {
  // Step 1: Generate QR code
  app.post('/api/bilibili/qrcode', async (_req, reply) => {
    try {
      const result = await biliGet('/x/passport-login/web/qrcode/generate')
      if (result.code !== 0) {
        return reply.status(500).send({ error: result.message || '生成二维码失败' })
      }
      return reply.send({
        url: result.data.url,
        qrcode_key: result.data.qrcode_key,
      })
    } catch (err) {
      return reply.status(500).send({ error: '无法连接 Bilibili' })
    }
  })

  // Step 2: Poll login status
  app.get('/api/bilibili/qrcode/check', async (req, reply) => {
    const { key } = req.query as { key?: string }
    if (!key) return reply.status(400).send({ error: 'qrcode_key required' })

    try {
      const result = await biliGet(`/x/passport-login/web/qrcode/poll?qrcode_key=${key}`)
      if (result.code !== 0) {
        return reply.status(500).send({ error: result.message || '轮询失败' })
      }

      const statusCode = result.data.code
      // 86101: not scanned | 86090: scanned, waiting confirm | 86038: expired
      // 0: success (data.url contains the token URL)
      if (statusCode === 0) {
        // Login success — exchange the token for cookies
        const tokenUrl = result.data.url
        if (tokenUrl) {
          const cookies = await exchangeCookies(tokenUrl)
          const cookiePath = saveCookies(cookies)
          return reply.send({ status: 'success', cookiePath, message: '登录成功' })
        }
        return reply.send({ status: 'success', message: '登录成功' })
      }

      if (statusCode === 86101) return reply.send({ status: 'waiting', message: '等待扫码' })
      if (statusCode === 86090) return reply.send({ status: 'scanned', message: '已扫码，请在手机上确认' })
      if (statusCode === 86038) return reply.send({ status: 'expired', message: '二维码已过期' })

      return reply.send({ status: 'unknown', code: statusCode })
    } catch {
      return reply.status(500).send({ error: '轮询失败' })
    }
  })

  // Check if cookies file exists
  app.get('/api/bilibili/status', async (_req, reply) => {
    const cookiePath = getCookiePath()
    return reply.send({ loggedIn: existsSync(cookiePath), cookiePath })
  })
}

async function exchangeCookies(tokenUrl: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const url = new URL(tokenUrl)
    const req = httpRequest({
      hostname: url.hostname,
      path: url.pathname + url.search,
      method: 'GET',
      headers: { 'User-Agent': 'PureDown/1.0', 'Referer': 'https://www.bilibili.com/' },
    }, (res) => {
      const setCookies = res.headers['set-cookie']
      if (setCookies && setCookies.length > 0) {
        // Convert Set-Cookie headers to Netscape cookie format for yt-dlp
        const cookies = setCookies.map(c => {
          const parts = c.split(';')[0] // "name=value"
          // Netscape format: domain\tTRUE\tpath\tFALSE\texpiry\tname\tvalue
          const domain = '.bilibili.com'
          const cookieMain = parts.trim()
          const eq = cookieMain.indexOf('=')
          const name = cookieMain.slice(0, eq)
          const value = cookieMain.slice(eq + 1)
          const expiry = Math.floor(Date.now() / 1000) + 365 * 86400
          return [domain, 'TRUE', '/', 'FALSE', String(expiry), name, value].join('\t')
        }).join('\n')
        resolve('# Netscape HTTP Cookie File\n# Generated by PureDown\n\n' + cookies + '\n')
      } else {
        reject(new Error('No cookies in response'))
      }
    })
    req.on('error', reject)
    req.end()
  })
}

function getCookiePath(): string {
  return process.env.COOKIES_FILE || join(downloadManager.getOutputDir(), 'bilibili-cookies.txt')
}

function saveCookies(content: string): string {
  const cookiePath = getCookiePath()
  const dir = dirname(cookiePath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(cookiePath, content, 'utf-8')
  return cookiePath
}
